[Defaults]
; Battery charge percentage at approx. 6pm, use 80 to 85% to maximise longevity
charge_percent=85

; Minimum grid percent if you need blackout protection set this to 30% otherwise leave at 10%
min_grid_percent=10

; Battery minimum percentage before solar production the next day to calculate excess
discharge_percent=10

; Average house hold usage in kW
average_usage=0.5

; Average air con usage in kW
aircon=0.5

; The temperature when you usually turn on your air con
aircon_cool_temp=26
aircon_heat_temp=23

; Your timezone
timezone=Australia/Sydney

; Your location for BoM hourly weather forecast data
lat=-33.8566
lon=151.2152

; The angle of the sun above the horizon when solar production is high enough to fully support the base house load,
; usually between 20 to 30 degrees depending on the direction your panels face and their tilt and latitude from the equator
start_angle=25
drop_off_angle=25

; Most optomistic charge/discharge rate possible, used to calculate likely imports/exports not limit them
max_charge_rate=5.0
max_discharge_rate=5.0

; All prices below are in dollars

; Unlike the above settings this is where to set the charge rate limit
charge_rate=5.0

; What is the cost of power outside peak times and the 3 hours of free power
shoulder_rate=0.385

; What is the cost of power during the peak period
peak_rate=0.517

; Daily Connection fee
conn_fee=2.068

; Discount for not importing more than 60Wh between 6pm and 8pm
discount=1

; target amount in dollars to export
price_target=1.2

; Unlike the above settings this is where to set the charge rate limit
charge_rate=5.0

[FreePowerTime]
; Free power from the grid times eg from 11am to 2pm
start_hour=11
end_hour=14

[BestExportTime]
; Time of the day when you get the most money sending power to the grid eg from 6pm to 8pm
start_hour=18
end_hour=20

; Maximum kW to send to the grid while exporting, usually 5kW for a single phase connection
max_rate_kW=6

; Feed in tariff for excess power sent to grid in dollars
max_kWh_at_high_fit=10
fit_rate=0.15
remainder_fit=0.06

[NextBestExportTime]
; Next best time of the day when you still get money for grid exports eg from 8pm to 9pm
start_hour1=16
end_hour1=18
start_hour2=20
end_hour2=21

; Maximum kW to send to the grid while exporting, usually 5kW for a single phase connection
max_rate_kW=5

; Feed in tariff for excess power sent to grid in dollars
fit_rate=0.06

[FoxESS]
; Fox ESS Cloud API key
apikey=

[Solcast]
; Solcast.com.au API key
apikey=
siteid1=

; Only add if you need a 2nd direction and/or have more than 1 solar system
siteid2=

[Forecast.Solar]
; Estimated solar system degredation in percent
degredation1=
degredation2=

; forecast.solar forecasts -- seem less reliable compared to solcast forecasts
tilt1=
az1=
size1=

; Only add if you need a 2nd direction and/or have more than 1 solar system
tilt2=
az2=
size2=
